// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaVSnB3FNTCp6B0bftNW3n-9z8vinJ1sw',
    appId: '1:228711345636:web:e84ce55d85139ffb7debf1',
    messagingSenderId: '228711345636',
    projectId: 'ku-chat-d875d',
    authDomain: 'ku-chat-d875d.firebaseapp.com',
    storageBucket: 'ku-chat-d875d.firebasestorage.app',
    measurementId: 'G-B6V2V6HQSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDpEnjxTAZ_MQVC6anpcPv_ySUGTyRgI',
    appId: '1:228711345636:android:60577376091126227debf1',
    messagingSenderId: '228711345636',
    projectId: 'ku-chat-d875d',
    storageBucket: 'ku-chat-d875d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEryWEijRd_ZCitAGNDploB0TIkOFKRc',
    appId: '1:228711345636:ios:edc71cb4b22405197debf1',
    messagingSenderId: '228711345636',
    projectId: 'ku-chat-d875d',
    storageBucket: 'ku-chat-d875d.firebasestorage.app',
    iosBundleId: 'com.example.kuKonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnEryWEijRd_ZCitAGNDploB0TIkOFKRc',
    appId: '1:228711345636:ios:edc71cb4b22405197debf1',
    messagingSenderId: '228711345636',
    projectId: 'ku-chat-d875d',
    storageBucket: 'ku-chat-d875d.firebasestorage.app',
    iosBundleId: 'com.example.kuKonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaVSnB3FNTCp6B0bftNW3n-9z8vinJ1sw',
    appId: '1:228711345636:web:567068bc80acc6d47debf1',
    messagingSenderId: '228711345636',
    projectId: 'ku-chat-d875d',
    authDomain: 'ku-chat-d875d.firebaseapp.com',
    storageBucket: 'ku-chat-d875d.firebasestorage.app',
    measurementId: 'G-613W4ZCSQN',
  );
}
